language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: 4bd4b4b6-152d-463e-8574-808be102f84f
 app: fast-tundra-11242
 run: "rake db:migrate"
 on:
  all_branches: true